---
title: "R Notebook"
output: pdf_document
---

```{r}
HMC = function (U, grad_U, epsilon, L, current_q)
{
  q = current_q
  ### a line to reject state with a given gradient, a way of restraining to the positive value of q
  ### in the case of the exponential case, probably not the best way of doing it
  if(grad_U(q)< -1e5) return (current_q)
  p = rnorm(length(q),0,1) # independent standard normal variates
  current_p = p
  
  # Make a half step for momentum at the beginning
  p = p - epsilon * grad_U(q) / 2
  
  # Alternate full steps for position and momentum
  for (i in 1:L)
  {
    # Make a full step for the position
    q = q + epsilon * p
    # Make a full step for the momentum, except at end of trajectory
    if (i!=L) p = p - epsilon * grad_U(q)
  }
  
  # Make a half step for momentum at the end.
  p = p - epsilon * grad_U(q) / 2
  
  # Negate momentum at end of trajectory to make the proposal symmetric
  p = -p
  
  # Evaluate potential and kinetic energies at start and end of trajectory
  current_U = U(current_q)
  current_K = sum(current_p^2) / 2
  proposed_U = U(q)
  proposed_K = sum(p^2) / 2
  
  # Accept or reject the state at end of trajectory, returning either
  # the position at the end of the trajectory or the initial position
  if (runif(1) < exp(current_U-proposed_U+current_K-proposed_K))
  {
    return (q) # accept
  }
  else
  {
    return (current_q) # reject
  }
  
}
```


# Test1: 
Exponential Distribution with $\lambda =1$
$$
f(x) = e^{-x}\qquad x>0
$$
$$
U(x) = -\log f(x) = x\qquad x>0
$$
$$
\dot{U}(x) = 1\qquad x>0
$$
```{r}
U = function(x){
  if(x>0){
    return (x)
  }
  else{
    return (0)
  }
}

grad_U = function(x) {
  if(x>=0){
    return (1)
  }
  else{
    ### a coding for "reject" sample, actually the exponential is NOT define for x<0
    return (-1.5e5)
  }
}


N <- 1000000
q <- 0
epsilon <- .01
L <- 10
output <- rep(0,N)


for (i in 1:N){
  q <- HMC (U, grad_U, epsilon, L, q)
  output[i] <- q
}

plot(output)
hist(output[500:N])
```

# Test2: 
Standard Normal Distribution
$$
f(x) \propto  e^{-x^2/2}
$$
$$
U(x) = -\log f(x) = x^2/2
$$
$$
\dot{U}(x) = x
$$
```{r}
U = function(x) x^2/2
grad_U = function(x) x

N <- 10000
q <- 0
epsilon <- .001
L <- 1000
output <- rep(0,N)


for (i in 1:N){
  q <- HMC (U, grad_U, epsilon, L, q)
  output[i] <- q
}
```

# Test3 Multivariate Normal
By taking 3-dimensional case with zero mean.
$$
f_X(x_1,x_2,x_3)\propto \frac{1}{\sqrt{|\Sigma|}} \exp(-\frac{1}{2}\textbf x^T\Sigma^{-1} \textbf x)
$$

```{r}
U = function(x) t(x) %*% sigma_inv %*% x/2
grad_U = function(x) sigma_inv %*% x

sigma_inv = diag(1,3,3)

N <- 100000
q <- c(0,0,0)
epsilon <- .01
L <- 10
output <- matrix(0,N,3)


for (i in 1:N){
  q <- HMC (U, grad_U, epsilon, L, q)
  output[i,1:3] <- q
}
plot(output[1000:N,1],output[1000:N,2])
```


```{r}
U = function(x) t(x) %*% sigma_inv %*% x/2
grad_U = function(x) sigma_inv %*% x
library(matlib)

sigma = matrix(1,2,2)
sigma[1,2] = 1/2
sigma[2,1] = 1/2
sigma_inv = inv(sigma)

N <- 100000
q <- c(0,0)
epsilon <- .01
L <- 10
output <- matrix(0,N,2)


for (i in 1:N){
  q <- HMC (U, grad_U, epsilon, L, q)
  output[i,1:2] <- q
}
plot(output[1000:N,1],output[1000:N,2])
```

